name: gooey_carousel
description: Package to implements a gooey carousel created by gskinner team
version: 0.1.2
author: Flutterando Team <david@flutterando.com.br>
homepage: https://flutterando.com.br/
git: https://github.com/davidsdearaujo/gooey_carousel
repository: https://github.com/davidsdearaujo/gooey_carousel

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg